name: Create Session Folders and Copy Files

on: [push]

jobs:
  create_folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify Node.js version 20

      - name: Create session folders and copy files
        run: |
          node -e "
          const fs = require('fs').promises; 
          const path = require('path');

          const baseDir = path.join(__dirname, 'session');
          const filesPerFolder = 500;

          async function createFoldersAndCopyFiles() {
            try {
              const files = await fs.readdir(baseDir);
              const totalFiles = files.length;
              let folderIndex = 1;

              for (let i = 0; i < totalFiles; i += filesPerFolder) {
                const folderName = folderIndex === 1 ? 'session' : `session${folderIndex}`;
                const folderPath = path.join(baseDir, folderName);

                await fs.mkdir(folderPath, { recursive: true });
                console.log(`Created folder: ${folderName}`);
                
                const filesToCopy = files.slice(i, i + filesPerFolder);
                for (const file of filesToCopy) {
                  const srcFilePath = path.join(baseDir, file);
                  const destFilePath = path.join(folderPath, file);
                  await fs.copyFile(srcFilePath, destFilePath);
                  console.log(`Copied ${file} to ${folderName}`);
                }
                folderIndex++;
              }
            } catch (err) {
              console.error('Error:', err);
            }
          }

          createFoldersAndCopyFiles();
          "
