name: Create Folders

on:
  push:
    branches:
      - main  # Change as needed

jobs:
  create_folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Create session folders
        run: |
          echo "const fs = require('fs');" > createFolders.js
          echo "const path = require('path');" >> createFolders.js
          echo "const baseDir = path.join(__dirname, 'session');" >> createFolders.js
          echo "const filesPerFolder = 500;" >> createFolders.js
          echo "fs.promises.readdir(baseDir)" >> createFolders.js
          echo "  .then(files => {" >> createFolders.js
          echo "    const totalFiles = files.length;" >> createFolders.js
          echo "    let folderIndex = 1;" >> createFolders.js
          echo "" >> createFolders.js
          echo "    for (let i = 0; i < totalFiles; i += filesPerFolder) {" >> createFolders.js
          echo "      const folderName = folderIndex === 1 ? 'session' : \`session\${folderIndex}\`;" >> createFolders.js
          echo "      const folderPath = path.join(baseDir, folderName);" >> createFolders.js
          echo "      fs.promises.mkdir(folderPath, { recursive: true })" >> createFolders.js
          echo "        .then(() => {" >> createFolders.js
          echo "          console.log(\`Created folder: \${folderName}\`);" >> createFolders.js
          echo "        });" >> createFolders.js
          echo "      folderIndex++;" >> createFolders.js
          echo "    }" >> createFolders.js
          echo "  })" >> createFolders.js
          echo "  .catch(err => console.error('Error reading directory:', err));" >> createFolders.js

          # Run the Node.js script
          node createFolders.js
