name: Organize Files

on:
  push:
    branches:
      - main

jobs:
  organize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Organize files
        run: |
          # Create folders for organized files
          mkdir -p session_1
          mkdir -p session_2
          mkdir -p session_3

          # Move the first 500 files to session_1
          ls session | head -n 500 | xargs -I {} mv session/{} session_1/
          
          # Move the next 500 files to session_2
          ls session | head -n 1000 | tail -n 500 | xargs -I {} mv session/{} session_2/
          
          # Move the next 1000 files to session_3
          ls session | head -n 1500 | tail -n 1000 | xargs -I {} mv session/{} session_3/

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add session_1 session_2 session_3
          git commit -m "Organized files into folders" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
